---
title: "R_001-Learning_Methods"
author: "Stone_Hou"
date: '`r Sys.Date()`'
output:
  html_notebook:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 4
  html_document:
    toc: yes
    toc_depth: '4'
---


# R_001-Learning_Methods 学习R的方法

> [学习R的方法](http://www.cnblogs.com/cloudtj/articles/5148848.html)

## 学习 R 的方法

知识和耐心，是成为强者的唯一方法。

- 通过阅读来学习。
包括了阅读经典的教材、代码、论文、学习公开课。

- 通过牛人来学习。
包括同行的聚会、讨论、大牛的博客、微博、twitter、RSS。

- 通过练习来学习。
包括代码练习题、参加kaggle比赛、解决实际工作中的难题。

- 通过分享来学习。
包括自己写笔记、写博客、写书、翻译书，和同伴分享交流、培训新人。

## 必备工具

下载 R and RStudio.

基础

[Try R](http://tryr.codeschool.com/) 非常适合R语言初学者，简短的代码，并能提示错误，不会产生挫败感

拓宽技能

看这里 [The Beginner's Guide to R](https://www.computerworld.com/article/2497143/business-intelligence/business-intelligence-beginner-s-guide-to-r-introduction.html) 大概30页，帮助你安装R，加载数据，进行分析，画图等一些常见知识。.

习惯养成

R Style Guide 教你如何写可读性强的代码，便于分享.

寻求帮助

如果你想了解R函数与包 Rdocumentation.org, 就去找R文档。

提出问题

StackOverflow,这个网站就不说了吧，先去找看一下有没有类似的问题，一般有！！！，如果没有就提问，基本都会得到回应，请保持提问的态度和姿势！

还有一个： CrossValidated Q&A community.

R语言社区论坛

R bloggers,去遨游吧，都是业内大牛

深入研究

如果你觉得你可以了, Advanced R 性能研究方向的，男神写的书.

Shiny

Shiny可以满足你骚，浪，爱得瑟的工具


## 阅读清单

### 一、初学入门：

《R in Action》[r-in-action](https://livebook.manning.com/#!/book/r-in-action/)
从统计角度入手，分高中低三部分由浅入深的讲解了如何用R来实现统计分析。


《The Art of_R Programming》
从程序编写的角度入手，对R的本身特点进行了清晰的介绍。

《learning R》
这本书没有单纯的讲语法，而是和数据分析的流程结合了起来，从数据获取到数据整理再到分析和报告，有一气呵成的感觉，此外最后两章讲如何写稳健的R代码以及写包都是非常精彩的。

### 二、统计进阶：

《A Handbook of Statistical Analyses_Using_R》

《Modern Applied Statistics With S》
这两本书基本上涵盖了统计的一些高阶内容，例如多元分析、多层回归模型、荟萃分析、生存分析等内容。案例丰富，公式不多，值得反复学习参考。

### 三、科学计算：

《Introduction to Scientific Programming and Simulation Using R》

《Mastering Scientific Computing with R》
除了统计分析外，独特之处在于使用R来做数值分析，如求根，最优化，数值积分。还包括了一些常见的模拟技术。书后的习题和最后的案例非常有用。

### 四、数据挖掘：

《Practical Data Science with R》
以R本身的扩展包和函数入手，很有体系的介绍了数据科学的各个方面。

《An Introduction to Statistical Learning》这本书可以说是另一本数据挖掘大作《The Elements of Statistical Learning》的R实现手册，体系结构基本一致，更强调用R来实现，更难得的地方是提供了很好的习题。

《Data Mining with R Learning with Case Studies》
《Machine Learning for Hackers》
两本侧重于数据挖掘的R书，全是以案例为线索，示范的代码量很大。跟一遍下来会有很大的收获。

《Data Mining explain using R》
用基本函数来实现各种机器学习算法，对理解算法底层很有帮助。

《Data Science in R》
以案例为主的书，需要一定的数据挖掘基础。

### 五、数据绘图：

《ggplot2 Elegant Graphics for Data Analysis》
ggplot2还有什么好说的呢，R中最优秀的绘图包，但由于近期该包升级很快，这书显得有些过时。好在中文版进行了大幅更新，即将面世。

《R Graphics Cookbook》这本书也是RStudio公司的人出的，似乎是Hadley的学生吧，主要是各种ggplot2包的例子，也包括了用其它包来画图，建议通读一遍。

### 六、参考手册：

《R Cookbook》

《R in a Nutshell》

有时候我们需要类似词典的案头参考手册，以方便随时查阅。又或者可以通读一遍以查漏补缺。上面两本书虽然有些厚度，但仍然推荐之。后者的中文版也在翻译状态。

### 七、高级编程：

《R Programming for Bioinformatics》

《software for data analysis programming with R》

如果你是初学者，不要去看上面两本书。如果你想进阶为专家级R用户，那你需要精读它们。前者讲解了R少为人知的一面，例如字符处理、正则表达和XML，还有报错处理以及与其它语言的交互。后者更是编写生产级代码的圣经指南。

《Advanced R programming》Hadley的力作，清楚的讲解了R的函数式编程思想和写R包的各种细节，要迈入R高手，不得不读。

## R语言相关数据集

### 如何使用R内置的数据集
R在datasets包中提供了100多个可以使用的数据集|通过data()函数加载入内存
```{r datasets}
data()
dim(data()$results)
data()$results
data()$results[,4]
```

### 向量

rivers #北美141条河流长度

state.abb #美国50个州的双字母缩写

state.area #美国50个州的面积

state.name #美国50个州的全称

euro #欧元汇率，长度为11，每个元素都有命名

landmasses #48个陆地的面积，每个都有命名

precip #长度为70的命名向量

### 因子

state.region #美国50个州的地理分类

state.division #美国50个州的分类，9个类别

### 矩阵、数组

crimtab #3000个男性罪犯左手中指长度和身高关系

HairEyeColor #592人头发颜色、眼睛颜色和性别的频数

occupatimnalStatus #英国男性父子职业联系

euro.cross #11种货币的汇率矩阵

freeny.x #每个季度影响收入四个因素的记录

state.x77 #美国50个州的八个指标

USPersonalExpenditure #5个年份在5个消费方向的数据

VADeaths #1940年弗吉尼亚州死亡率（每千人）

volcano #某火山区的地理信息（10米×10米的网格）

WorldPhones #8个区域在7个年份的电话总数

iris3 #3种鸢尾花形态数据

Titanic #泰坦尼克乘员统计

UCBAdmissions #伯克利分校1973年院系、录取和性别的频数

### 类矩阵

Harman74.cor #145个儿童24个心理指标的相关系数矩阵

eurodist #欧洲12个城市的距离矩阵，只有下三角部分

Harman23.cor #305个女孩八个形态指标的相关系数矩阵

### 数据框

BOD #随水质的提高，生化反应对氧的需求（mg/l）随时间（天）的变化

cars #1920年代汽车速度对刹车距离的影响

chickwts #不同饮食种类对小鸡生长速度的影响

esoph #法国的一个食管癌病例对照研究

faithful #一个间歇泉的爆发时间和持续时间

Formaldehyde #两种方法测定甲醛浓度时分光光度计的读数

Freeny #每季度收入和其他四因素的记录

dating from #配对的病例对照数据，用于条件logistic回归

InsectSprays #使用不同杀虫剂时昆虫数目

iris #3种鸢尾花形态数据

LifeCycleSavings #50个国家的存款率

longley #强共线性的宏观经济数据

morley #光速测量试验数据

mtcars #32辆汽车在11个指标上的数据

OrchardSprays #使用拉丁方设计研究不同喷雾剂对蜜蜂的影响

PlantGrowth #三种处理方式对植物产量的影响

airquality #纽约1973年5-9月每日空气质量

anscombe #四组x-y数据，虽有相似的统计量，但实际数据差别较大

attenu #多个观测站对加利福尼亚23次地震的观测数据

attitude #30个部门在七个方面的调查结果，调查结果是同一部门35个职员赞成的百分比

beaver1 #一只海狸每10分钟的体温数据，共114条数据

beaver2 #另一只海狸每10分钟的体温数据，共100条数据

### 类数据框

Indometh #某药物的药物动力学数据

Loblolly #火炬松的高度、年龄和种源

Orange #桔子树生长数据

Theoph #茶碱药动学数据

ChickWeight #饮食对鸡生长的影响

CO2 #耐寒植物CO2摄取的差异

DNase #若干次试验中，DNase浓度和光密度的关系

### 时间序列数据

freeny.y #每季度收入

JohnsonJohnson #1960-1980年每季度Johnson Johnson股票的红利

LakeHuron #1875-1972年某一湖泊水位的记录

lh #黄体生成素水平，10分钟测量一次

lynx #1821-1934年加拿大猞猁数据

nhtemp #1912-1971年每年平均温度

Nile #1871-1970尼罗河流量

nottem #1920-1939每月大气温度

presidents #1945-1974年每季度美国总统支持率

UKDriverDeaths #1969-1984年每月英国司机死亡或严重伤害的数目

sunspot.month #1749-1997每月太阳黑子数

sunspot.year #1700-1988每年太阳黑子数

sunspots #1749-1983每月太阳黑子数

treering #归一化的树木年轮数据

UKgas #1960-1986每月英国天然气消耗

USAccDeaths #1973-1978美国每月意外死亡人数

uspop #1790–1970美国每十年一次的人口总数（百万为单位）

WWWusage #每分钟网络连接数

Seatbelts #多变量时间序列。和UKDriverDeaths时间段相同，反映更多因素。

EuStockMarkets #多变量时间序列。欧洲股市四个主要指标的每个工作日记录，共1860条记录。

airmiles #美国1937-1960年客运里程营收（实际售出机位乘以飞行哩数）

AirPassengers #Box & Jenkins航空公司1949-1960年每月国际航线乘客数

austres #澳大利亚1971-1994每季度人口数（以千为单位）

BJsales #有关销售的一个时间序列

BJsales.lead #前一指标的先行指标（leading indicator）

co2 #1959-1997年每月大气co2浓度（ppm）

discoveries #1860-1959年每年巨大发现或发明的个数

ldeaths #1974-1979年英国每月支气管炎、肺气肿和哮喘的死亡率

fdeaths #前述死亡率的女性部分

mdeaths #前述死亡率的男性部分



## 阅读建议

- 在阅读时做笔记，以记下一些重点或心得

- 在阅读代码时，要在 R 环境中亲手键入代码并理解其意义

- 坚持练习,尝试利用身边的数据进行应用分析

- 理解扩展包和函数背后的原理

## 网络资源
- [R语言官方站](http://www.r-project.org/)

- [R-blogger](http://www.r-bloggers.com/)

- [R语言资源汇总](https://github.com/qinwf/awesome-R)

- [R语言搜索引擎](http://www.rseek.org/)

- [R函数在线帮助](http://www.rdocumentation.org/)

- [关于R的问答网站](http://stackoverflow.com/questions/tagged/r)

- [一个入门级的R在线教程](http://tryr.codeschool.com/)

- [交互式的R在线教程](https://www.datacamp.com/)

- [统计之都](http://cos.name/)

- [各种cheatsheet](http://cran.r-project.org/doc/contrib/Short-refcard.pdf)

- [rstudio各种cheatsheet](http://www.rstudio.com/resources/cheatsheets/)

- [Euler Project](https://projecteuler.net/)

- [kaggle](http://www.kaggle.com/)

