---
title: "R Delete Duplicated Value"
author: "Stone_Hou"
date: "`r Sys.Date()`"
output:
  html_notebook:
    number_sections: yes
    theme: readable
    toc: yes
    toc_depth: 4
---


# R Notebook Delete Duplicated Value

## 1. Question-Delete Duplicated Value

一列数据有几百万个，如何去掉多余重复的（重复的只保留一个），得到没有重复数据的序列？

## 2. Answer

** 可以尝试用`unique(x)`,`unique`对于一个向量管用，对于`matrix`、`data frame`那些就不管用了。

** 另外一个是`?duplicated`

```{r duplicated ex0}
x <- c("Anne","anne","bkk")
y <- tolower(x)
duplicated(y)
# [1] FALSE  TRUE FALSE

# R语言 如何去掉一个向量中重复的元素
# 例如：a=c(1,2,3,1,3)怎样得到向量c(1,2,3)?拜托
a <- c(1,2,3,1,3)

# !duplicated去除重复元素
a <- a[!duplicated(a)];a
# [1] 1 2 3

# unique去除重复元素
a <- c(1,2,3,1,3)
unique(a)
# [1] 1 2 3

# 一张data.frame的数据中，一列日期有重复值，不知道如何进行判断和剔除。
test <- data.frame(x = c(1:10, 1:3), y=1:13);test
test[!duplicated(test$x),]
#     x  y
# 1   1  1
# 2   2  2
# 3   3  3
# 4   4  4
# 5   5  5
# 6   6  6
# 7   7  7
# 8   8  8
# 9   9  9
# 10 10 10

# 如果data.frame多变量重复值怎么判断呢？下列数据集df：
df <- data.frame(id1 = c(rep(1,3),rep(2, 3)),
                 id2 = c(rep(2,3),rep(3, 3)),
                 id3 = c(1, 2, 1, 4, 5, 5)                 
                 )
df
#   id1 id2 id3
# 1   1   2   1
# 2   1   2   2
# 3   1   2   1
# 4   2   3   4
# 5   2   3   5
# 6   2   3   5

# 如果仅以id2去重复值会得到,
df[!duplicated(df$id2),]
#   id1 id2 id3
# 1   1   2   1
# 4   2   3   4

# 删掉所有列上都重复的
df[!duplicated(df),]
#   id1 id2 id3
# 1   1   2   1
# 2   1   2   2
# 4   2   3   4
# 5   2   3   5

# 选择性的删除第2列第3列重复的
df[!duplicated(df[,c(2,3)]),]
#   id1 id2 id3
# 1   1   2   1
# 2   1   2   2
# 4   2   3   4
# 5   2   3   5

base::unique(df)  # 一行搞定啊
#   id1 id2
# 1   1   2
# 4   2   3

```


###  duplicated delete duplicate value


```{r duplicated ex1}
# Record Current Date and time
DateTime <- format(Sys.time(), "%Y-%m-%d %H-%M-%S")

# load stop_word file, one line as one element, 
# character vector
stop_word_file_path <- file.choose()
# stop_word_file_path
# [1] "E:\\03-Download\\Github\\xiangxing98.github.io\\R_Learning\\stop_words_duplicated_no_unique.utf8.txt"

stop_word_file_directory <- dirname(stop_word_file_path)
# stop_word_file_directory
# [1] "E:/03-Download/Github/xiangxing98.github.io/R_Learning"

# scan and read stop_words_duplicated_no_unique.utf8.txt
stop_word <- scan(stop_word_file_path, sep="\n", what="", encoding="UTF-8")

# 删掉所有列上都重复的并赋值给新的变量
# (stop_word_unique <- stop_word[!duplicated(stop_word)])
stop_word_unique <- stop_word[!duplicated(stop_word)]

# 保存去除重复后的向量到新的文件
new_file_name <- paste("stop_words_unique-",DateTime,".utf8.txt", sep = "")

# sort stop_word_unique
stop_word_unique <- sort(stop_word_unique)

# output to txt
write.table(stop_word_unique, file = paste(stop_word_file_directory, new_file_name,sep = "/"), row.names = F, quote = F)
# save(stop_word_unique, file = paste(stop_word_file_directory, new_file_name,sep = "/"))
# ?save()
```

### Another duplicated() example

```{r duplicated ex2 }
# 另外一个duplicated()例子
# duplicated() 找出重复出现的元素。给出一例子
test <- c(21,22,22,23,22,23,24)
# 构建一个布尔向量，索引  
duplicated(test)
# [1] FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE

# 看得出duplicated()给出的是判断坐标：首次出现的22，函数给的值是F，但再次出现就成T了。
indicator <- duplicated(test)

# 把重复的坐标的值选出来(indicator中是TRUE的对应的坐标)
test[indicator]
# [1] 22 22 23

# 统计频次，注意不包括第一次出现的那次
table(test[indicator])
# 22 23 
# 2  1 

# 这是重复出现了几次(不包括首次) 所以你要的加1就行了。
table(test[indicator])+1
# 22 23 
# 3  2

```

