# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

#Alias
alias subl="D:/Program\ Files/Sublime\ Text\ 3/sublime_text.exe"
alias editplus="D:/Program\ Files/EditPlus/editplus.exe"

# Enable tab completion
source ~/git-completion.bash

# text colors!
dark="\[\033[0;30m\]"
green="\[\033[0;32m\]"
blue="\[\033[0;34m\]"
purple="\[\033[0;35m\]"
reset="\[\033[0m\]"

# background colors!
bg_dark="\[\033[01;40m\]"
bg_red="\[\033[01;41m\]"
bgGreen="\[\033[01;42m\]"
bg_yellow="\[\033[01;43m\]"
bg_blue="\[\033[01;44m\]"
bg_purple="\[\033[01;45m\]"
bg_sky_blue="\[\033[01;46m\]"
bg_light_blue="\[\033[01;47m\]"
#bg_reset="\[\033[0m\]"

# Change command prompt
source ~/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1
# '\u' adds the name of the current user to the prompt
# '\$(__git_ps1)' adds git-related stuff
# '\W' adds the name of the current directory
# '\w' adds the name of the current directory and path
export PS1="$green[\u@\h]$green\$(__git_ps1)$blue \w $reset $bgGreen\t $reset$ $reset"

#==== Define the color, for more information ,please refer to https://wiki.archlinux.org/index.php/Color_Bash_Prompt
#export GREEN=32
#export RED=31
#export BLUE=34
#export YELLOW=43
#export MAGENTA=35
#export WHITE=47
#
#export PS1="\[$GREEN\]\t\[$RED\]-\[$BLUE\]\u\[$YELLOW\]\[$YELLOW\]\w\[\033[m\]\[$MAGENTA\]\$(__git_ps1)\[$WHITE\]\$ "
#export PS1='\[\033[01;32m\][\u@\h\[\033[01;34m\] \w$(__git_ps1 " (%s)")]\[\033[01;34m\]\$ \[\033[00m\]]'
